### ISSUE TITLE
About How to use 

### ISSUE THREAD

**Issue by LiJiajun000322** [pjh5672/easy-YOLOv8#1]
Hello,

Thank you very much for providing this code, it has been very helpful to me. I am a beginner in deep learning, and I would like to ask for some help regarding how to use a custom dataset with this code. After converting my annotations to the COCO format, I noticed that my dataset does not have the imageToid content. Which file in the code should I use to generate this?

Thank you!

**Comment by pjh5672** [comment]
Hello @LiJiajun000322 !
imageToid cotents belong to **[your dataset].anno.json** file in cfg directory that is automatically generated when your dataset is loaded using **[your dataset].data.yaml** file. (see toy.anno.json and toy.data.yaml for example)  
You can refer to the generating source code from **dataloader/dataset.py** 
![image](https://github.com/user-attachments/assets/d887a62e-0017-4121-b276-9b5b1f3ae437)

**Comment by LiJiajun000322** [comment]
Thank you for your help; I have figured out how to train and infer on my own dataset!
However, I have another question and hope it won't bother you.
I want to return images and labels from two paths because my dataset contains paired images (stereo images). How should I modify the dataset-related code to handle this? My custom YAML file can only return images from one path for one view.

**Comment by pjh5672** [comment]
@LiJiajun000322 Well done ! 
You can modify code(red box section) and cfg/your data.yaml to get two paths for images.
- data.yaml
  + replace `train_dir: images/path1` with `train_dir:\n - images/path1\n - images/path2\n` ("\n" means escape sequence.)
  + ![image](https://github.com/user-attachments/assets/4aa300d0-dcaa-427c-83cb-30bf3aa77a66)

- dataset.py
  + when you modify data.yaml like above, you can get image_dir for list-typed, not str-typed. So you can add outer for-loop(modify 31 line) to read and append whole paths of images into `self.image_path` variable. 
  + ![image](https://github.com/user-attachments/assets/47871c3e-139e-41ca-b489-e435b09f566c)

That's what you try to do.

**Comment by LiJiajun000322** [comment]
Really Thank You!!!! Gonna try it

**Comment by jhpark6** [comment]
👍

**Comment by LiJiajun000322** [comment]
![question](https://github.com/user-attachments/assets/1fcd8209-74ee-42b5-b91e-99838312676d)

**Comment by pjh5672** [comment]
Hello, @LiJiajun000322 
Could you run with toy.data.yaml ? I've updated toy.data.yaml and the corresponding dataset in assets/samples directory.
You could delete toy.anno.json file and run script to newly generate toy.anno.json for checking above error, then It would be good hint that you could run with your dataset cfg file.

**Comment by LiJiajun000322** [comment]
OK, I will try it ! Thanks!
